# Generated by Django 4.1.4 on 2023-09-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.loandetails'),
        ),
        migrations.CreateModel(
            name='PatternSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_code', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=450)),
                ('city_name', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=6)),
                ('bank_name', models.CharField(max_length=56)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loandetails')),
            ],
        ),
        migrations.CreateModel(
            name='ChannalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing', models.CharField(choices=[('direct sourcing', 'direct'), ('pattern sourcing', 'pattern')], max_length=250)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChannalPattern', to='core.loandetails')),
            ],
        ),
    ]
