# Generated by Django 4.1.4 on 2023-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('agent', 'AGENT'), ('manager', 'MANAGER')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
