# Generated by Django 4.1.4 on 2023-09-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupationdetails',
            name='document_image',
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='document_image',
            field=models.FileField(default=1, upload_to='applicant-details/'),
            preserve_default=False,
        ),
    ]
