# Generated by Django 4.1.4 on 2023-09-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationdetails',
            old_name='other',
            new_name='document_image',
        ),
    ]
