# Generated by Django 4.1.4 on 2023-09-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing', models.CharField(choices=[('direct', 'direct sourcing'), ('pattern', 'pattern sourcing')], max_length=250)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChannalPattern', to='core.loandetails')),
            ],
        ),
        migrations.CreateModel(
            name='PatternSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_code', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=450)),
                ('city_name', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=6)),
                ('bank_name', models.CharField(max_length=56)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loandetails')),
            ],
        ),
        migrations.AddField(
            model_name='disbursement',
            name='irr_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='occupationalDocuments'),
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='occupationalDocuments'),
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='itr',
            field=models.FileField(blank=True, null=True, upload_to='occupationalDocuments'),
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='offer_later',
            field=models.FileField(blank=True, null=True, upload_to='occupationalDocuments'),
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='role',
            field=models.CharField(choices=[('soloried', 'SOLORIED'), ('self employed', 'SELF EMPLOYED'), ('partnership', 'PARTNERSHIP'), ('proprietor', 'PROPRIETOR'), ('other', 'OTHER')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='occupationalDocuments'),
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='shop_act',
            field=models.FileField(blank=True, null=True, upload_to='occupationalDocuments'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='emi_duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disbursement', to='core.loandetails'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='state',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonalDetails', to='core.loandetails'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
