# Generated by Django 4.1.4 on 2023-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disbursement_emi_amount_patternsourcing_bank_paas1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationdetails',
            name='role',
            field=models.CharField(choices=[('salaried', 'SALARIED'), ('self employed', 'SELF EMPLOYED'), ('partnership', 'PARTNERSHIP'), ('proprietor', 'PROPRIETOR'), ('other', 'OTHER')], max_length=50),
        ),
    ]
