# Generated by Django 4.1.4 on 2023-09-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personaldetails_vehicle_id_patternsourcing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channalpattern',
            name='sourcing',
            field=models.CharField(choices=[('direct', 'direct sourcing'), ('pattern', 'pattern sourcing')], max_length=250),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonalDetails', to='core.loandetails'),
        ),
    ]
