# Generated by Django 4.1.4 on 2023-09-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_occupationdetails_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupationdetails',
            name='document_image',
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='document_image',
            field=models.ManyToManyField(to='core.documentimages'),
        ),
    ]
