# Generated by Django 4.1.4 on 2023-09-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_occupationdetails_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationdetails',
            name='applicant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.personaldetails'),
        ),
        migrations.AlterField(
            model_name='occupationdetails',
            name='role',
            field=models.CharField(blank=True, choices=[('salaried', 'SALARIED'), ('self employed', 'SELF EMPLOYED'), ('partnership', 'PARTNERSHIP'), ('proprietor', 'PROPRIETOR'), ('other', 'OTHER')], max_length=50),
        ),
    ]
