# Generated by Django 4.1.4 on 2023-09-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_channalpattern_sourcing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disbursement', to='core.loandetails'),
        ),
    ]
