# Generated by Django 4.1.4 on 2023-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_disbursement_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='state',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
