# Generated by Django 4.1.4 on 2023-09-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_occupationdetails_document_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledocuments',
            old_name='appcant',
            new_name='applicant',
        ),
    ]
