# Generated by Django 4.1.4 on 2023-09-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vehicledocuments_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbrement',
            name='vehicle_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.vehicledetails'),
            preserve_default=False,
        ),
    ]
