# Generated by Django 4.1.4 on 2023-08-29 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_active_customuser_is_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('loan_amount', models.CharField(max_length=15)),
                ('net_amount', models.CharField(max_length=15)),
                ('emi_duration', models.CharField(choices=[('24 month', '24'), ('36 month', '36'), ('48 month', '48'), ('60 month', '60')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=150)),
                ('state_code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_card', models.FileField(upload_to='VehicleDocuments/')),
                ('insurance', models.FileField(upload_to='VehicleDocuments/')),
                ('form_29_30', models.FileField(upload_to='VehicleDocuments/')),
                ('form_34_35', models.FileField(upload_to='VehicleDocuments/')),
                ('bank_noc', models.FileField(upload_to='VehicleDocuments/')),
                ('rto_noc', models.FileField(upload_to='VehicleDocuments/')),
                ('form_28', models.FileField(upload_to='VehicleDocuments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appcant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.occupationdetails')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=150)),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_model', models.CharField(max_length=250)),
                ('vehicle_number', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'MR'), ('mrs', 'MRS'), ('other', 'OTHER')], max_length=150)),
                ('applicant_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(default='INDIA', max_length=150)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicledetails')),
            ],
        ),
        migrations.AddField(
            model_name='occupationdetails',
            name='appcant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personaldetails'),
        ),
        migrations.CreateModel(
            name='ApplicantDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=150)),
                ('document_image', models.FileField(upload_to='applicant-details/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.occupationdetails')),
                ('appcant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personaldetails')),
            ],
        ),
    ]
